### ISSUE TITLE
Split providerQuestions and applicantQuestions +more

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/client#57]

**Comment by mystreamer** [comment]
Fix: Set "None selected" as question default and only enable the "Start QnA" button or "Ask" button once a question has been selected
b50d3ee873a91a9da9eee150ae56850d9e47b891
Feature: Show the summary and stopping the session for the both users, when one user wants to quit => Q&A Session
Fix: System thinks logged in, even when user does not exist anymore (Heroku restarted, DB wiped)

**Comment by mystreamer** [comment]
f2fc4f62fd0eb97bf3c9981c70470307795cd2cb
