### ISSUE TITLE
Fix Bugs related to feedback

### ISSUE THREAD

**Issue by johannauzh** [sopra-fs22-group-02/client#66]

**Comment by mystreamer** [comment]
- Fix: Default value of "nearest to" when creating a new place => PlaceRegister
- Fix: Slots which are already taken still show up as available on the "apply events" page
- Authentication and authorization parts are lacking. Even though the dashboard page is secured, it is possible to access the profile and placeregister pages as an unauthenticated user.
- As a not logged-in user, it is possible to use application features, i.e., creating a slot ad.

**Comment by mystreamer** [comment]
06b7096beb9a734122f356cc2a6f0c7543e3ede5
